// netlify/functions/send-digest.js
// Sends the lead digest email via Resend

export default async function handler(req, context) {
  if (req.method !== 'POST') {
    return Response.json({ error: 'Method not allowed' }, { status: 405 })
  }

  const { email, leads } = await req.json()

  if (!email || !leads?.length) {
    return Response.json({ error: 'Missing email or leads' }, { status: 400 })
  }

  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  })

  // Build HTML email
  const leadRows = leads.map((l, i) => {
    const marketers = l.marketers?.length
      ? l.marketers.map(m => `<div style="margin:4px 0;font-size:13px;color:#555;">👤 <strong>${m.name}</strong>${m.title ? ` — ${m.title}` : ''}</div>`).join('')
      : '<div style="font-size:13px;color:#999;">No contacts found</div>'

    return `
      <div style="background:#f9f7ff;border-radius:12px;padding:16px;margin-bottom:12px;border:1px solid #e0d8ff;">
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:10px;">
          <div style="width:36px;height:36px;border-radius:8px;background:#7B52F4;color:white;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:16px;flex-shrink:0;">${l.company?.[0]}</div>
          <div>
            <div style="font-weight:800;font-size:15px;color:#0D0D0D;">${l.company}</div>
            <div style="font-size:12px;color:#888;">📊 ${l.etf} · <strong style="color:#7B52F4;">${l.ticker || ''}</strong></div>
          </div>
          ${l.linkedin ? `<a href="${l.linkedin}" style="margin-left:auto;background:#0A66C2;color:white;padding:5px 12px;border-radius:100px;text-decoration:none;font-size:12px;font-weight:700;white-space:nowrap;">in LinkedIn</a>` : ''}
        </div>
        <div style="border-top:1px solid #e0d8ff;padding-top:10px;">
          <div style="font-size:10px;font-weight:800;letter-spacing:0.12em;color:#aaa;text-transform:uppercase;margin-bottom:6px;">Marketing Contacts</div>
          ${marketers}
        </div>
      </div>`
  }).join('')

  const html = `
    <div style="font-family:'Inter',Arial,sans-serif;max-width:600px;margin:0 auto;background:#7B52F4;border-radius:20px;overflow:hidden;">
      <div style="padding:32px 32px 0;">
        <div style="display:inline-block;background:#FFD600;color:#0D0D0D;font-size:11px;font-weight:800;letter-spacing:0.15em;text-transform:uppercase;padding:4px 12px;border-radius:100px;margin-bottom:16px;">ETF Lead Digest · 7-Day</div>
        <h1 style="margin:0 0 8px;font-size:36px;font-weight:900;color:white;line-height:1.0;letter-spacing:-0.04em;">new ETFs.<br><span style="color:#FFD600;">find the team.</span></h1>
        <p style="color:rgba(255,255,255,0.7);font-size:15px;margin:0 0 24px;">${leads.length} new ETF launches this week — ${dateStr}</p>
      </div>
      <div style="background:white;margin:0 16px 16px;border-radius:16px;padding:20px;">
        ${leadRows}
      </div>
      <p style="text-align:center;font-size:12px;color:rgba(255,255,255,0.4);padding:0 0 24px;">Generated by Blossom ETF Monitor · Data from SEC EDGAR &amp; public web</p>
    </div>`

  // Send via Resend
  const resendRes = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: process.env.FROM_EMAIL || 'onboarding@resend.dev',
      to: email,
      subject: `🌸 ETF Lead Digest — ${dateStr}`,
      html,
    })
  })

  if (!resendRes.ok) {
    const err = await resendRes.text()
    return Response.json({ error: `Resend error: ${err}` }, { status: 500 })
  }

  return Response.json({ success: true })
}
